S390: Add convert_helpers.h implementation for hw-dfp.
Currently, there does not exist a convert_helpers.h implementation
on s390 for hardware decimal floating point.
The result ist, that the one in sysdeps/generic/. is used.
If you try to link a program with libdfp.so, you'll get linker errors:
libdfp.so: undefined reference to `combine_and_truncd64'
libdfp.so: undefined reference to `combine_and_truncd32'
collect2: error: ld returned 1 exit status

Building with software-dfp, these functions are implemented.

This patch implements a specific convert_helpers.h for s390 with
hardware-dfp. Afterwards a program can link without these errors.

Signed-off-by: Stefan Liebler <stli@linux.vnet.ibm.com>