Clean unused variable in configure test
Setting CFLAGS to '-Wall -Werror' before calling configure yields the
following error message:

    conftest.c:16:13: error: variable 'foo' set but not used [-Werror=unused-but-set-variable]
      static int foo;

The use of the variable in the configuration test is not necessary to
attain the test objective, i.e.: verify the presence of
register_printf_type in glibc.  This patch removes the unused variable.

Signed-off-by: Gabriel F. T. Gomes <gabriel@inconstante.eti.br>