libdfp: Fix test test-bfp-conversion due to build and more errors.
On s390, building this test fails due to:
In function ‘main’:
test-bfp-conversions.c:347:3: error: unknown type name ‘sdtf_type’
   sdtf_type *sdtfp;
test-bfp-conversions.c:348:3: error: unknown type name ‘ddtf_type’
   ddtf_type *ddtfp;
...

As information: __LDBL_MANT_DIG__ has the value ...
... 113 on s390x
... 106 on power
... 64 on intel.

The test builds, if both structs are defined in case of
"if __LDBL_MANT_DIG__ == 106 || __LDBL_MANT_DIG__ == 113".

Afterwards there were some confusing errors like:
1.234500e+01 = (long double) 1.234500e+01; /* _Decimal32 */ in: /home/stli/libdfp/src/tests/test-bfp-conversions.c: 557
63  Error:   Expected: "1.234500e+01"
              Result:   "1.234500e+01"
in: /home/stli/libdfp/src/tests/test-bfp-conversions.c:271

Formatting the output with a higher precision showed the difference:
1.234500e+01 = (long double) 1.234500e+01; /* _Decimal32 */ in: /home/stli/libdfp/src/tests/test-bfp-conversions.c: 557
63  Error:   Expected: "1.23450000000000006394884621840902e+01"
              Result:   "1.23450000000000000000000000000000e+01"
in: /home/stli/libdfp/src/tests/test-bfp-conversions.c:271

Thus I applied a higher precision with the format specifiers field
and added the missing literal float/long double suffix to input- or expected-value.

All tests with tdtf_tests failed, because the power-specific variant was executed.
Thus the power variant is now executed in case of "if __LDBL_MANT_DIG__ == 106".
S390 uses the same variant as Intel.
This clears failing tdtf_tests in test-bfp-conversions.out.

Furthermore, there was dead code in lines from 523 to 552 in second
"if defined(__DECIMAL_BID_FORMAT__) && __LDBL_MANT_DIG__ == 64":
    451:#if defined(__DECIMAL_BID_FORMAT__) && __LDBL_MANT_DIG__ == 64
    452:# define DECIMAL_PRINTF_BUF_SIZE 65	/* ((DECIMAL128_PMAX + 14) * 2) + 1 */
    506:#else
    523:# if defined(__DECIMAL_BID_FORMAT__) && __LDBL_MANT_DIG__ == 64
    524:#  define DECIMAL_PRINTF_BUF_SIZE 65	/* ((DECIMAL128_PMAX + 14) * 2) + 1 */
    552:# else
    576:# endif /* ! defined(__DECIMAL_BID_FORMAT__) && __LDBL_MANT_DIG__ == 64  */
    593:#endif /* ! defined(__DECIMAL_BID_FORMAT__) && __LDBL_MANT_DIG__ == 64  */
The deleted code - for sdxf_tests and ddxt_tests - was identical to first if section.

On s390, two tftd_tests fail, due to different long double data-type than on power.
Thus I changed them to:
  {__LINE__, 12.3456789L, 12.3456789DL,  "%.34DDe"},
  {__LINE__, 999999999999999999999999999999999.0L, 999999999999999999999999999999999.0DL,  "%.34DDe"},

The result on s390:
1.2345678900000000000000000000000000e+01 = (_Decimal128) 1.2345678900000000000000000000000000e+01; /* long double */ in: /home/stli/libdfp/src/tests/test-bfp-conversions.c: 511
expected: +0,000,000,000,000,000,000,000,000,123,456,789E-7
retval:   +1,234,567,890,000,000,000,000,000,000,000,000E-32
57  Success: Expected: "1.2345678900000000000000000000000000e+01"
              Result:   "1.2345678900000000000000000000000000e+01"

9.9999999999999999999999999999999900e+32 = (_Decimal128) 9.9999999999999999999999999999999900e+32; /* long double */ in: /home/stli/libdfp/src/tests/test-bfp-conversions.c: 511
expected: +9,999,999,999,999,999,999,999,999,999,999,990E-1
retval:   +0,999,999,999,999,999,999,999,999,999,999,999E+0
62  Success: Expected: "9.99999999999999999999999999999999e+32"
              Result:   "9.99999999999999999999999999999999e+32"
in: /home/stli/libdfp/src/tests/test-bfp-conversions.c:168

The result on power:
1.2345678899999999999999999999999920e+01 = (_Decimal128) 1.2345678899999999999999999999999921e+01; /* long double */ in: /home/stli/libdfpDir/src/tests/test-bfp-conversions.c: 511
expected: +0,000,000,000,000,000,000,000,000,123,456,789E-7
retval:   +1,234,567,889,999,999,999,999,999,999,999,992E-32
57  Error:   Expected: "1.2345678900000000000000000000000000e+01"
              Result:   "1.2345678899999999999999999999999920e+01"
in: /home/stli/libdfpDir/src/tests/test-bfp-conversions.c:163

1.0000000000000000000000000000000000e+33 = (_Decimal128) 1.0000000000000000000000000000000000e+33; /* long double */ in: /home/stli/libdfpDir/src/tests/test-bfp-conversions.c: 511
expected: +9,999,999,999,999,999,999,999,999,999,999,990E-1
retval:   +1,000,000,000,000,000,000,000,000,000,000,000E+0
62  Error:   Expected: "9.9999999999999999999999999999999900e+32"
              Result:   "1.0000000000000000000000000000000000e+33"
in: /home/stli/libdfpDir/src/tests/test-bfp-conversions.c:168

What should we do in these two cases? Shall they fail on power
or should we specify different expected values in case of
"if __LDBL_MANT_DIG__ == 113 ... else ..."?

Signed-off-by: Stefan Liebler <stli@linux.vnet.ibm.com>